#!/bin/sh
## problem_1_4
## Mac Radigan

  d=${0%/*}
  root=${0%/*}/..
  export PYTHONPATH=.
  export PYTHONPATH=${PYTHONPATH}:${d}:${root}/library 
  if [ "Darwin" != $(uname) ]; 
  then
    python3 -O -m problem_1_4 $*
  else
    /opt/anaconda3/bin/python3 -O -m problem_1_4 $*
  fi


## *EOF*
