#!/bin/sh
## problem_1_4
## Mac Radigan

  d=${0%/*}; f=${0##*/}; n=${f%.*}; e=${f##*.}
  root=${0%/*}/..
  export PYTHONPATH=.
  export PYTHONPATH=${PYTHONPATH}:${d}:${root}/library 
  if [ "Darwin" != $(uname) ]; 
  then
    python3 -O -m $n $*
  else
    /opt/anaconda3/bin/python3 -O -m $n $*
  fi


## *EOF*
